// <auto-generated />
using System;
using Hogeri.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hogeri.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20231019134249_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Hogeri.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("CashInvested")
                        .HasColumnType("double");

                    b.Property<string>("CoinType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GeneralAccountName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Hogeri.Models.AccountOwner", b =>
                {
                    b.Property<string>("OwnerId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("OwnerId");

                    b.ToTable("AccountOwners");
                });

            modelBuilder.Entity("Hogeri.Models.AccountOwnerAccount", b =>
                {
                    b.Property<string>("OwnerId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.HasKey("OwnerId", "AccountId");

                    b.HasIndex("AccountId");

                    b.ToTable("AccountOwnerAccounts");
                });

            modelBuilder.Entity("Hogeri.Models.MyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MyEntities");
                });

            modelBuilder.Entity("Hogeri.Models.AccountOwnerAccount", b =>
                {
                    b.HasOne("Hogeri.Models.Account", "Account")
                        .WithMany("AccountOwnerAccounts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hogeri.Models.AccountOwner", "AccountOwner")
                        .WithMany("AccountOwnerAccounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("AccountOwner");
                });

            modelBuilder.Entity("Hogeri.Models.Account", b =>
                {
                    b.Navigation("AccountOwnerAccounts");
                });

            modelBuilder.Entity("Hogeri.Models.AccountOwner", b =>
                {
                    b.Navigation("AccountOwnerAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
